### PR TITLE
fix index out of bounds error on queries

### PR DESCRIPTION
**Pull request by kstep**
This change is [Reviewable](https://reviewable.io/reviews/tailhook/cantal/2)

### CODE REVIEW

**Comment by kstep** [comment]
The problem is while `target` in `vec_sum` is locked in size to the size of the first `src` snapshot in `sum_series`, and then `lst` (based on original `src`) is folded into the `target`, and there's some time between `src` size snapshot and `lst` initialization, so `src` has some time to change (grow in size).

This race results in `lst` (`source` in `vec_sum`) slightly longer (usually by 1) than `target`, hence "out of index bounds" error.

This fix uses iterators to avoid such situation, so processed size is limited to shortest vector (`target` in this case), so some last items from `src` can be skipped.

If this is critical, another fix is possible: in `sum_series` take full snapshot of `src`, and then use this snapshot both to initialize target vector and to build `chunk` (`lst`).

**Comment by tailhook** [comment]
I'm still not sure why this happens. We check that timestamps array of all meetrics are same. And number of items in metrics vector must be exactly the same as number of timestamps. And we operate on the copy of metrics so it can't be modified after we check it.

So I think there is something wrong in another place, like the place where we snapshot metrics. Still haven't enough time to investigate it yet.

Do you know which metric fails? Or at least which web page is current when this crash occurs?

**Comment by kstep** [comment]
It crashes when I try to load main stats page if cantal has run for several hours.

**Comment by tailhook** [comment]
Sorry for having this issue for a long time. We now have this issue on our production system with the recent `--keep-history 5min` option enabled. 

Notes to myself:
1. It looks like it happens when status page requests the data `/query.cbor`
2. When not looking at status page process do not crash
3. Process do not crash even when enabling "remote" and looking at grid for 60 remote servers

I still can't reproduce the issue on local tests, but I'm investigating it now.

**Comment by tailhook** [comment]
The offending query:
```
{
  "rules": {
    "q17": {
      "series": {
        "source": "Fine",
        "condition": [
          "And",
          [
            "RegexLike",
            "metric",
            "^disk\\.in_progress$"
          ],
          [
            "RegexLike",
            "device",
            "^sd[a-z]$"
          ]
        ]
      },
      "extract": [
        "HistoryByNum",
        1100
      ],
      "functions": [
        [
          "SumBy",
          "metric",
          "Ignore",
          true
        ]
      ]
    }
  }
}
```

**Comment by tailhook** [comment]
Another note to myself: in my setting it crashes at about 150-180 datapoints (i.e it works if we change `HistoryByNum` to 150), whereas --keep-history=5min means to keep in memory at least 150 datapoints. 

Any by the way, here is the traceback:
```
thread '<main>' panicked at 'index out of bounds: the len is 154 but the index is 154', ../src/libcollections/vec.rs:1167
stack backtrace:
   1:     0x7fb3fd1ba35f - std::sys::backtrace::tracing::imp::write::h3800f45f421043b8
   2:     0x7fb3fd1bdf0b - std::panicking::default_hook::_$u7b$$u7b$closure$u7d$$u7d$::h0ef6c8db532f55dc
   3:     0x7fb3fd1bdb93 - std::panicking::default_hook::hf3839060ccbb8764
   4:     0x7fb3fd1abbad - std::panicking::rust_panic_with_hook::h5dd7da6bb3d06020
   5:     0x7fb3fd1be151 - std::panicking::begin_panic::h9bf160aee246b9f6
   6:     0x7fb3fd1accaa - std::panicking::begin_panic_fmt::haf08a9a70a097ee1
   7:     0x7fb3fd1be0ee - rust_begin_unwind
   8:     0x7fb3fd1f3b9f - core::panicking::panic_fmt::h93df64e7370b5253
   9:     0x7fb3fd1f3d12 - core::panicking::panic_bounds_check::h1956babe18380ff8
  10:     0x7fb3fd0bc1f3 - cantal_query::functions::sum::sum_series::h6c2ff936a36625de
  11:     0x7fb3fd0be1ff - cantal_query::functions::sum::sum_series_by::h2bed8d29fa041de0
  12:     0x7fb3fd0b80ef - cantal_query::functions::_<impl rule..Function>::exec::hc3098026e644ad2e
  13:     0x7fb3fd0b6d17 - cantal_query::query::query_history::h6994be5474e8fe04
  14:     0x7fb3fcf5b156 - cantal_agent::server::resolve::hc7a545a57f81960d
  15:     0x7fb3fcf502dd - cantal_agent::server::Client::_read::h15f89985a083ab66
  16:     0x7fb3fcf4f974 - cantal_agent::server::Client::do_read::ha028f0e4544480e9
  17:     0x7fb3fcfa724d - _<server..Handler as mio..Handler>::ready::ha9fef1387cf5bccd
  18:     0x7fb3fcf4cbfb - cantal_agent::server::server_loop::h8054c02092bd3e56
  19:     0x7fb3fcef2d33 - cantal_agent::run::h263df7b9794748db
  20:     0x7fb3fcee7383 - cantal_agent::main::ha03a26a959418ac6
  21:     0x7fb3fd1bd7a8 - std::panicking::try::call::hbbf4746cba890ca7
  22:     0x7fb3fd1c7b7b - __rust_try
  23:     0x7fb3fd1c7b1e - __rust_maybe_catch_panic
  24:     0x7fb3fd1bd24e - std::rt::lang_start::hbcefdc316c2fbd45
  25:     0x7fb3fbc49ec4 - __libc_start_main
  26:     0x7fb3fcee7278 - <unknown>
  27:                0x0 - <unknown>
```

**Comment by tailhook** [comment]
Should be fixed by 5c1ebbe. Going to test tomorrow.

**Comment by tailhook** [comment]
It's confirmed that bug is gone on our servers. @kstep is it still meaningful for you?

**Comment by tailhook** [comment]
It looks like fixed on our cluster. Hopefully, it works for you too.

**Pull request closed without merging**
