### PR TITLE
ARM related patches

### PR DESCRIPTION
**Pull request by kstep**
I installed cantal to my Raspberry Pi 3 for system monitoring, and here are changes I had to make to make it compile and work on ARMv7/8.

Also, I introduced a new cli option `--interval` — the scan interval in milliseconds, defaults to 2 seconds (as it is now). Two seconds is too often for my Raspberry, it makes to consume too many CPU cycles, so I set this interval to 10 seconds.

---
This change is [Reviewable](https://reviewable.io/reviews/tailhook/cantal/1)

### CODE REVIEW

**Comment by kstep** [comment]
Also I want to add temperature metrics, though the code is a little dirty at the moment, so I want to take some time to polish it before creating PR.

**Comment by tailhook** [comment]
Looks great. Thanks!

Can you make a screenshot of it? Or alternatively I'm curious how it performs: number of metrics, scan time, memory usage, which are shown in the bottom part of sidebar (or in a `Beacon` message in a console)

**Comment by kstep** [comment]
Here's `htop`'s screenshot at the peak moment of system scanning.

2016-06-28-131821_1239x117_scrot

My system is [ArchLinux ARMv7](https://archlinuxarm.org/platforms/armv8/broadcom/raspberry-pi-3):

```
$ uname -a
Linux raspberry 4.4.13-2-ARCH #1 SMP Mon Jun 13 19:46:58 MDT 2016 armv7l GNU/Linux
$ free -m
              total        used        free      shared  buff/cache   available
Mem:            922          87         240           1         593         803
Swap:             0           0           0
$ uptime
 13:24:53 up 7 days, 15:24,  1 user,  load average: 0.02, 0.30, 0.44
```

**Comment by kstep** [comment]
It's gathering 1978 metrics, 195 processes.

**Comment by tailhook** [comment]
I mean the screenshot of the cantal itself, here is a scan time I'm still interested in (and memory and cpu usage are on the right):
cantal

**Comment by kstep** [comment]
It crashed with the following error during HTTP request serving a few minutes ago:

```
Jun 28 13:31:02 raspberry cantal-agent[14313]: [2016-06-28 13:31:02][WARN] cantal_agent::websock Invalid opcode 8
Jun 28 13:32:53 raspberry cantal-agent[14313]: [2016-06-28 13:32:53][WARN] cantal_agent::websock Invalid opcode 8
Jun 28 16:36:26 raspberry cantal-agent[14313]: thread '<main>' panicked at 'index out of bounds: the len is 579 but the index is 579', ../src/libcollections/ve
Jun 28 16:36:26 raspberry cantal-agent[14313]: note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Unfortunately, I haven't foreseen it, so I had to chance to gather backtrace. Anyway, here are stats after restart:

2016-06-28-164152_297x136_scrot

**Comment by tailhook** [comment]
Thanks!

Not sure what is the reason for the crash, so traceback would be appreciated.

Also, it looks like CPU graph is wrong because of changed interval. Do you use cantal for carbon/graphite rather than it's own web UI?

**Comment by kstep** [comment]
I use cantal built-in web client at the moment. I don't want to use heavier things, like carbon, graphite, etc. Just trying to keep things minimal. The UI inconsistencies are OK and understandable for me, at least for now.

**Comment by kstep** [comment]
It crashed again, now with `RUST_BACKTRACE` set. Here's backtrace:

```text
Jun 29 11:18:55 raspberry cantal-agent[15757]: thread '<main>' panicked at 'index out of bounds: the len is 474 but the index is 474', ../src/libcollections/ve
Jun 29 11:18:55 raspberry cantal-agent[15757]: stack backtrace:
Jun 29 11:18:56 raspberry cantal-agent[15757]:    1: 0x54d9224b - sys::backtrace::tracing::imp::write::hf670d8b6386d22deJcv
Jun 29 11:18:56 raspberry cantal-agent[15757]:    2: 0x54d950c3 - panicking::default_handler::_$u7b$$u7b$closure$u7d$$u7d$::closure.44482
Jun 29 11:18:56 raspberry cantal-agent[15757]:    3: 0x54d94c4f - panicking::default_handler::h8779de026b877d91YTz
Jun 29 11:18:56 raspberry cantal-agent[15757]:    4: 0x54d81c77 - sys_common::unwind::begin_unwind_inner::h3b511d4750e909fd20t
Jun 29 11:18:56 raspberry cantal-agent[15757]:    5: 0x54d821e7 - sys_common::unwind::begin_unwind_fmt::hfb02698582574ecb8Zt
Jun 29 11:18:56 raspberry cantal-agent[15757]:    6: 0x54d9177b - rust_begin_unwind
Jun 29 11:18:56 raspberry cantal-agent[15757]:    7: 0x54d9cefb - panicking::panic_fmt::h559080aff49c30cclcM
Jun 29 11:18:56 raspberry cantal-agent[15757]:    8: 0x54d9d0cf - panicking::panic_bounds_check::h60500edb60ab3e94rbM
Jun 29 11:18:56 raspberry cantal-agent[15757]:    9: 0x54ce03e7 - functions::sum::sum_series::h1f56086dd9a95023Xyf
Jun 29 11:18:56 raspberry cantal-agent[15757]:   10: 0x54cdbe97 - functions::Function::exec::h67667101e899112apLf
Jun 29 11:18:56 raspberry cantal-agent[15757]:   11: 0x54cd8fa7 - query::query_history::h58a9e17d25f7ba9fnff
Jun 29 11:18:56 raspberry cantal-agent[15757]:   12: 0x54b9689f - server::resolve::h9cd4ae954be369c8JBa
Jun 29 11:18:56 raspberry cantal-agent[15757]:   13: 0x54b8d23f - server::Client::_read::h3e9a17e7476cd247qwa
Jun 29 11:18:56 raspberry cantal-agent[15757]:   14: 0x54b8ca9f - server::Client::do_read::h7dd94583fca194a0Nva
Jun 29 11:18:56 raspberry cantal-agent[15757]:   15: 0x54bcf5cf - server::Handler.mio..Handler::ready::h4329ca2d05efa74057a
Jun 29 11:18:56 raspberry cantal-agent[15757]:   16: 0x54b8a5f7 - server::server_loop::h489802fe92f52680ulb
Jun 29 11:18:56 raspberry cantal-agent[15757]:   17: 0x54b3fabf - run::hef8e723fa9c9d8709bl
Jun 29 11:18:56 raspberry cantal-agent[15757]:   18: 0x54b34dff - main::ha44e9241b49e5cbeUal
Jun 29 11:18:56 raspberry cantal-agent[15757]:   19: 0x54d94817 - sys_common::unwind::try::try_fn::h5358980013828492550
Jun 29 11:18:56 raspberry cantal-agent[15757]:   20: 0x54d9170b - __rust_try
Jun 29 11:18:56 raspberry cantal-agent[15757]:   21: 0x54d9170b - __rust_try
```

There're a lot of repeating `__rust_try` entries in the backtrace, I omitted them.

**Comment by kstep** [comment]
I tracked down the error to `sum_series` function, which iterates by index instead of an iterator. Related PR #2.

**Pull request merged**
