### PR TITLE
Addition of LICENSE information

### PR DESCRIPTION
**Pull request by osvaldsson**
As communicated over email. This pull request is for the addition of a LICENSE file with the MIT license information to prevent misunderstanding in terms of the licensing.

I also added a short note in the README.rst with a similar Contribution section as is currently in cantal-py

By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

### CODE REVIEW

**Comment by tailhook** [comment]
Looks okayish. But can you split PR for LICENSE and other bundling changes? So that it's easier to review.

**Comment by osvaldsson** [comment]
Sorry, the original pull-request only included the license changes, it was not my intent to ask you to pull anything more recent than that as I am still working on those.

I'll change it so that it is only for the license related changes.

**Comment by osvaldsson** [comment]
I've updated the source repository and the pull request only includes the licensing file updates now.

**Comment by tailhook** [comment]
Merged. Thanks!

**Pull request merged**
